### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by jwright04** [juliancwirko/react-s-alert#1]
@juliancwirko you've created a really nice component here. I had a question for you about security.  What's to prevent someone from using a `<script>` tag when loading something like: 
```
Alert.error('Test message 3');
```

I'm concerned about XSS attacks.

**Comment by juliancwirko** [comment]
Hi, this is only accessible from your app so I think that only you could provide `<script>` tags there and of course you don't want to. Also you need to set up `html: true` to be able to display formated HTML which is provided by https://facebook.github.io/react/tips/dangerously-set-inner-html.html so I think XSS shouldn't be a problem, but of course if you have a good example of such use case let me know.

**Comment by jwright04** [comment]
Thanks for the response!  I'll keep playing around with it!!
