### ISSUE TITLE
Alert not disappearing on timeout

### ISSUE THREAD

**Issue by minfawang** [juliancwirko/react-s-alert#12]
You can see from the GIF the alert stays in the screen forever. I'm using the latest version (1.1.2). Is that a bug?
![alert-error](https://cloud.githubusercontent.com/assets/8814693/14773076/4133c786-0a5a-11e6-97e5-ee6e05dea7a6.gif)

**Comment by juliancwirko** [comment]
Hi, this is weird, is it working in the app? Not in the console. I'm curious, how do you run it in the console. How do you get the 'Alert' object here? It should be imported in the React app.

**Comment by minfawang** [comment]
Oh I just import the `Alert` object and append it in the global namespace. Something like
~~~javascript
import Alert from 'react-s-alert';
class MyComp extends React.Components {
  render() {
    global.Alert = Alert; // <-- So it's available in the console.
    // ...
  }
}
~~~
It the same as running in the app... Do you want any other information?

**Comment by juliancwirko** [comment]
Hmmm, I don't think that it will work like that. Basically what you need to do is to place <Alert> component somewhere in your main app component (in render) and then make calls like Alert.warning(...) etc. In the app it works well for me. You can check out the demo App source code for more information: https://github.com/juliancwirko/react-s-alert-demo

What is important:

[This line](https://github.com/juliancwirko/react-s-alert-demo/blob/master/app/components/homeView/Home.js#L237) and [calls to the Alert](https://github.com/juliancwirko/react-s-alert-demo/blob/master/app/components/homeView/Home.js#L35)

**Comment by minfawang** [comment]
Yes. I have placed an `<Alert />` element in the root of the app. It used to work before (like two weeks ago). I think only one `<Alert />` element for the whole app is enough, right?

**Comment by juliancwirko** [comment]
Yes, it should be one <Alert /> component, but you need to be sure that it is always available. 
I can reproduce that bug :/ Can you test it on version 1.1.0 or maybe 1.0.0? Or maybe you can create a small reproduction repository?

**Comment by minfawang** [comment]
Let me try to create a reproduction! First thank you for your help. Really appreciate it!

**Comment by juliancwirko** [comment]
Ok, that would be awesome :)

**Comment by zhaoyao91** [comment]
Hi, I encountered this problem in some apps too! fortunately one of them is a demo app and the code is in [github](https://github.com/zhaoyao91/number-war), and there is even an [online demo](http://number-war.pangkers.com/game) of this app so you can *try to reproduce* the problem right now (you can use username *bob* and password *123*). I cannot ensure this online demo will last for long time, but you can always run this meteor project locally to test.
By my experience, it rarely happens on PC, but often occurs on my galaxy s7 edge browser.

**Comment by juliancwirko** [comment]
Hey, I'll close it for now, if someone have good reproduction repo let me know.

**Comment by zentuit** [comment]
I'm seeing the same thing -- I don't have a good reproduction repo, but I've traced it and see that after the `handleCloseAlert` function has finished, the `render` is not fired again. In my particular case, the close button looks unresponsive; but in reality the `handleCloseAlert` fires and finishes also without the re-rendering.

I have 3 different components that use Alerts, but only 1 is displaying this behavior. If I find anything else out, I'll let you know.
