### ISSUE TITLE
Default position not working

### ISSUE THREAD

**Issue by nmaro** [juliancwirko/react-s-alert#13]
I must be doing an obvious mistake. Using

`<Alert onRouteClose={false} position="bottom" />`

The alerts still appear on the top right.

**Comment by juliancwirko** [comment]
Hi, In the newest version 1.1.2 it should be fixed. Also remember that even when you have configured position on <Alert /> component it could be overwritten in single Alert method call. So you need to be sure that you don't overwrite it in method calls.

Anyway when I have:

```
<Alert position="bottom" />
```
and call like:
```
Alert.warning('Test warning!');
```
It works like it should.

**Comment by nmaro** [comment]
Thanks it works now.
