### ISSUE TITLE
installing the package on meteor overwrites default underscore

### ISSUE THREAD

**Issue by voidale** [juliancwirko/react-s-alert#14]
I found that when I used the package the default _ was loadash and _.last _.first didn't work as expected.

**Comment by juliancwirko** [comment]
Hmmm, this is strange, maybe I should remove lodash dependency. I'll try to test it asap. Thanks.

**Comment by juliancwirko** [comment]
In 1.1.3 Lodash dependency is removed.

**Comment by voidale** [comment]
Thanks! :)
Dne 2. 5. 2016 17:56 napsal uživatel "Julian Ćwirko" <
notifications@github.com>:
