### ISSUE TITLE
UMD build?

### ISSUE THREAD

**Issue by DomKM** [juliancwirko/react-s-alert#16]
Your library looks great! Would you be open to providing a UMD build for use in non-Node environments (like via a CDN)?

**Comment by juliancwirko** [comment]
Hi, I'll try to look into it. I think that probably you just need to replace `transform-runtime` [here](https://github.com/juliancwirko/react-s-alert/blob/master/package.json#L32) with `transform-es2015-modules-umd`. You will also need to install the plugin. Here it is: https://www.npmjs.com/package/babel-plugin-transform-es2015-modules-umd

**Comment by juliancwirko** [comment]
in version 1.1.4 there is UMD build in the dist folder

**Comment by DomKM** [comment]
Thanks, @juliancwirko! Unfortunately, it doesn't seem to work for me. I get `Uncaught TypeError: Cannot read property 'Component' of undefined` from [here](https://github.com/juliancwirko/react-s-alert/blob/8e5c00490436e19db38be4a72fe8ac78e8c946ae/dist/SAlert.js#L280). I think your UMD build is not finding `window.React` correctly.

**Comment by juliancwirko** [comment]
Hi, could you create reproduction repository for me?

**Comment by juliancwirko** [comment]
Hey, I'll close it for now, if someone have good reproduction repo let me know.
