### ISSUE TITLE
Alert not working using require

### ISSUE THREAD

**Issue by Taieb** [juliancwirko/react-s-alert#17]
I am importing Alert with require but I got this error

> warning.js:45Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components)

Otherwise how to migrate from ES5 to ES2015 ?

**Comment by americaru** [comment]
+ 1, same question

**Comment by americaru** [comment]
`var Alert = require('react-s-alert').default;` is solving es5 require error

**Comment by Taieb** [comment]
I replaced reactify by Babelify and I used import so I solve this problem...

**Comment by juliancwirko** [comment]
Hi, I try to test it more with ES5, and fix the docs, but yeah, I encourage you to use ES2015 with Webpack or Babelify

**Comment by juliancwirko** [comment]
I don't want to change the lib for now. So I've just updated the readme file. You can import it just like @americaru said, it should work.
