### ISSUE TITLE
Close alert animation

### ISSUE THREAD

**Issue by vugman** [juliancwirko/react-s-alert#22]
Is it possible to do Alert.close(:id) or Alert.closeAll() animated?

Thanks

**Comment by juliancwirko** [comment]
Hi, some of them should have a closing animation, but not all of them, some of them has just 'fade out' effect. This is because it was difficult to manage timings in complicated animations and some other problematic stuff. But it probably could be implemented better.

**Comment by vugman** [comment]
Hey,

Thanks for the quick response.
I'm using a custom component for the alert (based on the original implementation). When i click on the alert i call this.props.handleClose() and then I see the animation. 
Yet, when I call Alert.closeAll() from outside of the component, there's no animation.

Is there a way I can get it to animate currently also when calling Alert.closeAll() ?

**Comment by juliancwirko** [comment]
Yes, the closeAll method just removes all alerts from the store. We could probably improve that, but for now there isn't a simple way to achieve it.

**Comment by vugman** [comment]
Ok, thanks.

Great work btw!

**Comment by pdfabbro** [comment]
Hi,

I'm not sure what you mean by "sAlert methods will return the already created alertId".  How do I get this alertId?
