### ISSUE TITLE
JSX as Message

### ISSUE THREAD

**Issue by mxmtsk** [juliancwirko/react-s-alert#23]
Hi,

is it possible to add JSX a message. I tried the following, but it's showing [object Object]. It's kind of obvious to use jsx so I'd kindly like to ask if you would consider adding support for jsx? (Or did I miss something and it's already possible?)

```javascript
        Alert.error(<div>
          {response.errors.map((error, index) => {(
            <div key={`ticket-error-${index}`}>
              {error.message}
            </div>
          )})}
        </div>, {
          position: 'top-right',
          effect: 'slide',
          beep: '/media/pop.mp3',
          html: true,
        });
```

**Comment by juliancwirko** [comment]
Hi, would it be what you need: https://github.com/juliancwirko/react-s-alert/pull/19 ?

**Comment by mxmtsk** [comment]
@juliancwirko Yes exactly, that would be what I need!

**Comment by juliancwirko** [comment]
Ok, I'll try to test and merge it today.

**Comment by juliancwirko** [comment]
Ok, in version 1.2.0 you should be able to do what you need.

**Comment by juliancwirko** [comment]
I'll close it for now. It should work. Let me know if you find any problems. Thanks.
