### ISSUE TITLE
_renderNewRootComponent

### ISSUE THREAD

**Issue by pcegarra** [juliancwirko/react-s-alert#25]
Im using meteor to display alerts when some vars changes.

```
trackNewOrders(){

    Tracker.autorun( (thisTracker) =>{
        var oldest = _.max(this.props.orders,(order) => {
          return order.clock;
        });
        if(oldest.clock){
          if (!_.findWhere(this.state.array, {'_id':oldest._id})) {
            Alert.success('New order, {
              position: 'top-right'
            });
            this.state.array.push(oldest);
          }
        }
    });
  } 
```

_renderNewRootComponent(): Render methods should be a pure function of props and state; triggering nested component updates from render is not allowed. If necessary, trigger nested updates in componentDidUpdate.

I dont understand that error

**Comment by ashwinimnnit** [comment]
even I'm getting the same error
