### ISSUE TITLE
Module not found: Error: Cannot resolve module 'react/lib/ReactMount'

### ISSUE THREAD

**Issue by AllenFang** [juliancwirko/react-s-alert#26]
If upgrade React to ```15.4.0```, will get the following error on webpacking
```
Module not found: Error: Cannot resolve module 'react/lib/ReactMount'
```

**Comment by juliancwirko** [comment]
Hi, I'll take a look into it soon.

**Comment by juliancwirko** [comment]
Hi, I'll update dependencies, but we don't use Webpack here so I don't think that this is the problem of this package. 

Do you use react-hot-loader in your webpack config? Maybe you should update it to version 3.

**Comment by AllenFang** [comment]
Sorry for lately reply, actually, we use webpack as our module bundlers and got this error when we take react 15.4.x. BTW, I also use the react hot loader@3. Thanks

**Comment by juliancwirko** [comment]
Ok, so I will close this for now. Feel free to comment here if there will be some other problems. Thanks.
