### ISSUE TITLE
Cannot use Component  instead of string message

### ISSUE THREAD

**Issue by mihaimariusbaciu** [juliancwirko/react-s-alert#27]
Using react-s-alert version 1.2.0

Warning:
Invalid prop `message` of type `object` supplied to `SAlertContent`, expected `string`.

What I found is that the SAlertContent propTypes have different values than the ones in the master branch
`message: _react2.default.PropTypes.string.isRequired,`.

It seems that the code on npm was not updated only the version.

Thank you for your time!

**Comment by juliancwirko** [comment]
Hi, you can try version 1.2.1
Oh, and thanks :)

**Comment by mihaimariusbaciu** [comment]
Works like a charm. I will close the issue.

Thank you!
