### ISSUE TITLE
Alert is not displaying

### ISSUE THREAD

**Issue by DinakaranS** [juliancwirko/react-s-alert#29]
Hi,

I have implemented react-s-alert. In my application but when i am triggering the alert its not displaying in my page. 

I am using sweet alert, material ui snackbar also, everything is working fine. I tried to increase the z-index, but no luck.

My application is a react, redux, router with google maps component implemented web app.

**Comment by juliancwirko** [comment]
Hi, it's hard to tell what is wrong based on your description. 
Have you included necessary css files? Do you have errors in the browser's console?

**Comment by DinakaranS** [comment]
import 'react-s-alert/dist/s-alert-default.css';
import 'react-s-alert/dist/s-alert-css-effects/slide.css';
import 'react-s-alert/dist/s-alert-css-effects/scale.css';
import 'react-s-alert/dist/s-alert-css-effects/bouncyflip.css';
import 'react-s-alert/dist/s-alert-css-effects/flip.css';
import 'react-s-alert/dist/s-alert-css-effects/genie.css';
import 'react-s-alert/dist/s-alert-css-effects/jelly.css';
import 'react-s-alert/dist/s-alert-css-effects/stackslide.css';

Yes, i have included all this in my index file. Also i necessary config in web pack.

FYI: I have a zindex file. My highest zindex is 1500. So i increase the .s-alert-box zindex to 2000. But no luck.

No errors in browser's console.

**Comment by juliancwirko** [comment]
Hmm, it is hard for me to debug it without a working demo :/ 
If you be willing to prepare reproduction github repo it will be much simpler to fix this problem.

You can also check the demo github repo: https://github.com/juliancwirko/react-s-alert-demo which is published here: http://react-s-alert.jsdemo.be/ Maybe this could be some kind of guide for you.

**Comment by DinakaranS** [comment]
Thanks, Oh i found the issue there was a spell mistake in my webpack. Now everything is working fine. 

I note onShow, onClose events present. I need onClick event. How to trigger this event.

**Comment by juliancwirko** [comment]
There isn't such event, but You can use custom template for this use case: https://github.com/juliancwirko/react-s-alert#overwrite-content-template-component

**Comment by DinakaranS** [comment]
Thanks

**Comment by stahlmanDesign** [comment]
I changed my `.s-alert-box` z-index to 1501 to and it now shows on top of popups that have a z-index of 1500
