### ISSUE TITLE
add useJSX support

### ISSUE THREAD

**Issue by Sburke0708** [juliancwirko/react-s-alert#33]
It would be great if we could add a `useJsx` param instead of only `useHtml`

**Comment by juliancwirko** [comment]
Hi, take a look at: https://github.com/juliancwirko/react-s-alert/pull/19

**Comment by juliancwirko** [comment]
Hi, I think the linked thread is a solution for your need. 
If you don't agree feel free to comment here. For now I'll close the issue. Thanks.
