### ISSUE TITLE
UNMET PEER DEPENDENCY prop-types@^15.5.4

### ISSUE THREAD

**Issue by davidbiller** [juliancwirko/react-s-alert#36]
I get this error Message, i think it´s because i use the new REACT Version.

Failed to compile.

Error in ./~/react-s-alert/dist/SAlert.js
Module not found: 'prop-types' in /Users/davidbiller/curious_web/node_modules/react-s-alert/dist

 @ ./~/react-s-alert/dist/SAlert.js 3:8-181

**Comment by juliancwirko** [comment]
Hi, does it work when you install prop-types ? `npm install prop-types`

**Comment by davidbiller** [comment]
Yes, i am sorry for that

**Comment by juliancwirko** [comment]
yes, but it should also work with older versions of react (before 15.5), I need to test it once again.
