### ISSUE TITLE
Error: Firefox.

### ISSUE THREAD

**Issue by lannex** [juliancwirko/react-s-alert#4]
Hi. 
In the firefox browser, it does not disappear after the animation effect.
(You can also check the demo page.)

Kind regards,

**Comment by juliancwirko** [comment]
You right :/ I'm sure that it worked, I need to investigate it. Thanks.

**Comment by juliancwirko** [comment]
ok there is a fix in v1.0.2, should work now

**Comment by lannex** [comment]
I've checked.
@juliancwirko Thanks a lot !
