### ISSUE TITLE
Upload style files to cdn

### ISSUE THREAD

**Issue by zhaoyao91** [juliancwirko/react-s-alert#42]
Hi, thanks for this package. Could you please put the style files into some cdn?

**Comment by juliancwirko** [comment]
Hi, yes this would be a good solution for some people. I'll look around for some options.

**Comment by juliancwirko** [comment]
Hi, actually we have something like: 
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-default.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/bouncyflip.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/flip.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/genie.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/jelly.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/scale.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/slide.css
https://cdn.jsdelivr.net/npm/react-s-alert@1.4.0/dist/s-alert-css-effects/stackslide.css

I'll add it to the documentation.
I'll close it now. Feel free to post your questions. Thanks.
