### ISSUE TITLE
Several <Alert /> render in one page

### ISSUE THREAD

**Issue by AllenFang** [juliancwirko/react-s-alert#47]
HI @juliancwirko, I found if I render multiple `react-s-alert` in a page, when one of alert triggering, the alert will popup twice. is it a bug or we should use only one `react-s-alert` in a page?

Thanks

**Comment by AllenFang** [comment]
BTW, the popup twice >> Actually, it's not perform as like a stack, The two alert popup are overlap.

**Comment by juliancwirko** [comment]
You should have only one `<Alert />` component in the app. In you main component or as colse as possible.

**Comment by AllenFang** [comment]
all right, thank you
