### ISSUE TITLE
specify default `configObject` for all alerts

### ISSUE THREAD

**Issue by satyanash** [juliancwirko/react-s-alert#48]
There needs to be a way to set default values for the alert configObject so every call to `Alert.success()`, `Alert.info()`,`Alert.warning()`,`Alert.error()` need not pass in the same object.
If a `configObject` is passed, it should override the default values set.

**Comment by satyanash** [comment]
Never mind. It is doable.

**Comment by juliancwirko** [comment]
I am not sure if I understand you, but it works like that. You can provide global settings on main component.
