### ISSUE TITLE
Type definition

### ISSUE THREAD

**Issue by mitsuruog** [juliancwirko/react-s-alert#55]
Does anyone has planned to have the type definition for TypeScript?

I am a big fan of this project. and I am using this a lot.
Thanks!!

**Comment by mitsuruog** [comment]
Alright, I'll make it.

**Comment by juliancwirko** [comment]
Sorry, I don' use Typescript with React yet, so I can't help here ;)

**Comment by mitsuruog** [comment]
No worry. since I made a new PR here, It will be able to use soon.

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/21230

**Comment by mitsuruog** [comment]
Merged. then we can use the type definition.

```
npm install @types/react-s-alert
```

let me know if it has any problem.
FYI @juliancwirko
