### ISSUE TITLE
Keep alert when redirect page.

### ISSUE THREAD

**Issue by tronghiep92** [juliancwirko/react-s-alert#57]
Hi guys,

After user login success, I did the following two things: 

- Alert success message by `react-s-alert`
- Redirect to /profile page

But redirect page has caused `react-s-alert` not working. Because the component has destroyed.

```js
class Login extends React.Component {
...
 login = () => {
   apiLogin().then(() => {
    Alert.success('login success');
    return Router.push('/profile');
   })
 }
...
```

Thanks

**Comment by juliancwirko** [comment]
You can always put `<Alert />` component somewhere in your layout, somewhere outside your app's content component. As close to the root component as possible. This should work.

**Comment by tronghiep92** [comment]
Thanks for your answer. I understand the problem.
But I'm using Next.js, I cannot put `<Alert />` to root component or near the root component.

**Comment by MikeSha** [comment]
Hey @nghiepit . Have you manage this issue?
