### ISSUE TITLE
`beep' property cause `_ is undefined' when used in isomorphic project.

### ISSUE THREAD

**Issue by tearsofphoenix** [juliancwirko/react-s-alert#6]
It will cause an undefined error when use `beep' property in isomorphic project. Bug may be in line 88, 93, 98 in file: dist/SAlertContent.js.

**Comment by juliancwirko** [comment]
you're right, there isn't lodash imported, I'll fix this asap.

**Comment by juliancwirko** [comment]
Ok, there is a new version `1.0.3`. Check it out.

**Comment by PEM--** [comment]
I confirm that it fixes the issue :+1:

**Comment by tearsofphoenix** [comment]
fixed! 👍🏻
