### ISSUE TITLE
Are there more color options?

### ISSUE THREAD

**Issue by tnoel999888** [juliancwirko/react-s-alert#67]
Hi, nice component, was just wondering if it's possible to use a different color than the default yellow?

**Comment by juliancwirko** [comment]
Hi, I don't want to provide more style settings because you can always overwrite css classes. Of course it depends on how you will use the lib. But you can always just copy the styles to your app and adjust as you want it.

**Comment by tnoel999888** [comment]
@juliancwirko ah right fair enough, thanks!
