### ISSUE TITLE
How to display only one similar error message out of multiple similar error messages

### ISSUE THREAD

**Issue by pavangond** [juliancwirko/react-s-alert#72]
In my react app, i have 4 react components in all of them i am refering react-s-alert .
for some reason i am getting network issue while displaying those errors using react-s-alert all are displaying network failed error message(total 4 similar error messages).

1. All four messages are similar, so now i want to display only one out of those similar error messages.
2. if i get 4 different error messages all 4 should display.

I refered doc i didn't get any idea

Is it possible or not..?

**Comment by juliancwirko** [comment]
Sorry, I need reproduction repo for that because I think I don't understand the problem.

**Comment by pavangond** [comment]
ok,

i have 3 click buttons, if i click on it, we will get error notifications 
![click](https://user-images.githubusercontent.com/34574384/45081765-8ba3d680-b115-11e8-89eb-ed4bf2998930.png)


 If i click on all buttons they will produce same error message (unique error message i.e Network error) .
![similar_error](https://user-images.githubusercontent.com/34574384/45081801-99f1f280-b115-11e8-8243-2b06b21ab857.png)



all the 3 error messages are same, instead of displaying all the 3 messages i want to display only 1 messages(bcz all convey same information).

we want like this :- 

![similar](https://user-images.githubusercontent.com/34574384/45081848-ac6c2c00-b115-11e8-8ff7-e5305c8e9da2.png)


How can i achieve it 
or
Is there any features we have, to display single error message instead of displaying multiple similar error messages ?

**Comment by pavangond** [comment]
We want to show max 5 messages so i can't make stack to false.

you can check if next error is the same as previous one and decide if you want to fire alert or not ?

where to register that check ?

can i get any example or prototype for it..
