### ISSUE TITLE
Run build without React

### ISSUE THREAD

**Issue by brianyang** [juliancwirko/react-s-alert#8]
I'm developing a Meteor app which includes React, and I'm getting the error that there are two copies of React

how can I remove the reference and build a new source in ./dist? 

thank you!

**Comment by juliancwirko** [comment]
Hi, how do you install React in Meteor? Do you use React from Meteor package or from Npm? I gues I could use React as a peerDependency here, it should help, but I need to test it.

**Comment by brianyang** [comment]
i just included the source in lib, thanks for your help

**Comment by juliancwirko** [comment]
Ok. I need to test it anyway. Could you tell me what version of React do you use and how do you install React in Meteor? Do you use old wayt do do it with Meteor packages? Or is it Npm with Meteor 1.3?
